# Generated by Django 4.0.1 on 2023-01-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criticalpath', '0004_coursepaymentsplits'),
        ('marketplace', '0003_alter_featuredcreators_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criticalpath.course')),
            ],
        ),
    ]
