# Generated by Django 4.0.1 on 2023-03-13 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criticalpath', '0008_ebook'),
        ('marketplace', '0005_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='ebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criticalpath.ebook'),
        ),
        migrations.CreateModel(
            name='FeaturedEbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField()),
                ('ebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criticalpath.ebook')),
            ],
        ),
    ]
