# Generated by Django 4.0.1 on 2023-03-30 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='currency_text',
            new_name='text',
        ),
    ]
