# Generated by Django 4.0.1 on 2023-05-21 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criticalpath', '0015_workshop_workshoppaymentsplits'),
        ('marketplace', '0008_rename_currency_text_currency_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criticalpath.workshop'),
        ),
    ]
