# Generated by Django 4.0.1 on 2022-12-24 00:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(validators=[django.core.validators.MinLengthValidator(3, 'Comment must be greater than 3 characters')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Not Published'), (1, 'Published'), (2, 'Archived')], default=0)),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')])),
                ('excerpt', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(3, 'Resource excerpt must be greater than 3 characters')])),
                ('cover_image', models.ImageField(blank=True, default='seo-card-image.png', null=True, upload_to='course/cover_images/')),
                ('price', models.PositiveIntegerField(default=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CriticalPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')])),
                ('description', models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(3, 'Journey description must be greater than 3 characters')])),
                ('objective', models.TextField()),
                ('cover_image', models.ImageField(blank=True, default='static/assets/img/seo-card-image.png', null=True, upload_to='journey/cover_images/%Y/%m/%D/')),
                ('price', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JourneyResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Not Published'), (1, 'Published'), (2, 'Archived')], default=0)),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'Resource name must be greater than 3 characters')])),
                ('excerpt', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(3, 'Resource excerpt must be greater than 3 characters')])),
                ('file', models.FileField(null=True, upload_to='resource/files/')),
                ('content', django_quill.fields.QuillField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, default='seo-card-image.png', null=True, upload_to='resource/cover_images/')),
                ('price', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criticalpath.resource')),
            ],
        ),
    ]
