# Generated by Django 4.0.1 on 2022-12-24 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criticalpath', '0001_initial'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.transaction'),
        ),
        migrations.AddField(
            model_name='reward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criticalpath.category'),
        ),
        migrations.AddField(
            model_name='resource',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journeyresources',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticalpath.journey'),
        ),
        migrations.AddField(
            model_name='journeyresources',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticalpath.resource'),
        ),
        migrations.AddField(
            model_name='journey',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criticalpath.category'),
        ),
        migrations.AddField(
            model_name='journey',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fav',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticalpath.journey'),
        ),
        migrations.AddField(
            model_name='fav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='criticalpath',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criticalpath.journey'),
        ),
        migrations.AddField(
            model_name='criticalpath',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criticalpath.resource'),
        ),
        migrations.AddField(
            model_name='courseresources',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticalpath.course'),
        ),
        migrations.AddField(
            model_name='courseresources',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticalpath.resource'),
        ),
        migrations.AddField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticalpath.journey'),
        ),
        migrations.AlterUniqueTogether(
            name='fav',
            unique_together={('journey', 'user')},
        ),
    ]
