# Generated by Django 4.0.1 on 2022-12-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticalpath', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resource/files/'),
        ),
    ]
