# Generated by Django 4.0.1 on 2023-01-29 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticalpath', '0004_coursepaymentsplits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='price',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
