# Generated by Django 4.0.1 on 2023-01-29 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticalpath', '0005_alter_resource_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=10000, validators=[django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
