# Generated by Django 4.0.1 on 2023-02-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticalpath', '0006_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='resource/videos/'),
        ),
    ]
