# Generated by Django 4.0.1 on 2023-03-09 04:15

import criticalpath.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criticalpath', '0007_resource_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Not Published'), (1, 'Published'), (2, 'Archived')], default=0)),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'Resource name must be greater than 3 characters')])),
                ('excerpt', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(3, 'Resource excerpt must be greater than 3 characters')])),
                ('file', models.FileField(blank=True, null=True, upload_to='resource/files/', validators=[criticalpath.models.file_size])),
                ('content', django_quill.fields.QuillField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, default='seo-card-image.png', null=True, upload_to='resource/cover_images/')),
                ('price', models.PositiveIntegerField(default=25000, validators=[django.core.validators.MaxValueValidator(25000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criticalpath.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
