# Generated by Django 4.0.1 on 2023-03-29 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criticalpath', '0008_ebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookPaymentSplits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticalpath.ebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
