# Generated by Django 4.0.1 on 2023-03-30 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticalpath', '0009_ebookpaymentsplits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
