# Generated by Django 4.0.1 on 2023-03-30 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticalpath', '0010_alter_ebook_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='price',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
