# Generated by Django 4.0.1 on 2023-03-31 05:01

import criticalpath.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_rename_currency_text_currency_text'),
        ('criticalpath', '0012_alter_ebook_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='excerpt',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(3, 'Course excerpt must be greater than 3 characters')]),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='excerpt',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(3, 'Ebook excerpt must be greater than 3 characters')]),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ebooks/files/', validators=[criticalpath.models.file_size]),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'Ebook title must be greater than 3 characters')]),
        ),
    ]
