# Generated by Django 4.0.1 on 2023-03-31 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_rename_currency_text_currency_text'),
        ('criticalpath', '0013_alter_course_excerpt_alter_ebook_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='currency_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marketplace.currency'),
        ),
    ]
