# Generated by Django 4.0.1 on 2023-05-21 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticalpath', '0015_workshop_workshoppaymentsplits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='excerpt',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(3, 'Workshop excerpt must be greater than 3 characters')]),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'Workshop title must be greater than 3 characters')]),
        ),
    ]
